[tool.black]
skip-string-normalization = true

[tool.pylint.messages_control]
max-line-length = 88
disable = [
  "bare-except",
  "missing-module-docstring",
  "logging-fstring-interpolation",
  "redefined-outer-name",
  "useless-return",
]
