name: 'Validate Pull Request'

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.py'
      - '**.tf'

jobs:
  format:
    name: 'Check format'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Python Format
        uses: psf/black@stable
        with:
          options: "--check --verbose"

  validate:
    name: 'Validate Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        working-directory: examples/simple
        run: terraform init -lock-timeout=300s

      - name: Terraform Validate
        working-directory: examples/simple
        run: terraform validate

  check_version:
    if: github.event.pull_request.head.repo.fork == false
    name: 'Check Module Version'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_level: warn
          validation_depth: 1

      - name: Check Tags
        env:
          TAG: v${{ steps.changelog_reader.outputs.version }}
        run: |
          # h/t Azeem (https://stackoverflow.com/a/76170179)
          if $(git show-ref --tags --verify --quiet refs/tags/${TAG}); then
            echo "Version $TAG already exists"
            exit 1
          fi
