name: 'Security Scans'

on:
  push:
    paths:
      - '**.py'
      - '**.tf'

permissions:
  contents: read
  security-events: write

jobs:
  sast:
    name: 'SAST scans'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        continue-on-error: true
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
